name: telemed
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts: 0.3.8
  toast: ^0.1.5
  simple_animations: ^1.1.3
  page_transition: ^1.1.4

  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2

  provider: ^4.0.4
  rflutter_alert: ^1.0.3
  flutter_spinkit: ^4.1.2+1

  font_awesome_flutter: ^8.4.0

  firebase_database: ^3.1.3
  firebase_messaging: ^6.0.13
  firebase_core: ^0.4.4+3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
